spring:
  datasource:
    url: jdbc:mysql://118.25.35.198:3306/electric?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1111
    name: electric
  flyway:
    schemas: ${spring.datasource.name}
    locations: classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: false
  profiles:
    active: dev
server:
  port: 8080

mybatis:
  type-aliases-package: com.gaoh.electric.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    database-id: mysql
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
pagehelper:
  helper-dialect: mysql
  reasonable: true
  page-size-zero: true
